const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const ROUTES={overview:'/',logs:'/logs',chat:'/chat',members:'/members',moderation:'/moderation',announce:'/announce',streams:'/streams',social:'/social',routing:'/routing',settings:'/settings',control:'/control'};
const savedGuild=(()=>{try{return localStorage.getItem('rs_guild')||''}catch{return ''}})();
const state={api:localStorage.getItem("rs_api")||location.origin,token:localStorage.getItem("rs_token")||"",guild:savedGuild||null,guilds:[],logs:[],config:{providers:{},routes:{}}};
window.rsState=state;const BUILD="sentinel-20260911-19";let pollTimer=null;
function rememberGuild(id){state.guild=String(id||'')||null;try{if(state.guild)localStorage.setItem('rs_guild',state.guild);else localStorage.removeItem('rs_guild')}catch{}}
function toast(t){const e=$("#toast");if(!e)return;e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),3000)}
function api(path,opts={}){const headers=Object.assign({"Content-Type":"application/json"},opts.headers||{});if(state.token)headers.Authorization=`Bearer ${state.token}`;return fetch(state.api.replace(/\/$/,"")+path,{...opts,headers,cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error((await r.text())||`${r.status} ${r.statusText}`);return r.status===204?{}:r.json()})}
function routeFor(v){return ROUTES[v]||ROUTES.overview}
function viewFor(path){const clean=(path||'/').replace(/\/+$/,'')||'/';return Object.keys(ROUTES).find(k=>ROUTES[k]===clean)||'overview'}
function showView(v,opts={}){if(!v)return;const path=routeFor(v);if(!opts.noHistory&&location.pathname!==path)history.pushState({sentinelView:v},'',path);$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const title=$("#pageTitle");if(title)title.textContent=v==='control'?'Server Control':v==='chat'?'Server Chat':v==='announce'?'Announcements':v==='streams'?'Livestreams':v==='social'?'Social Feeds':v==='logs'?'Live Logs':v.charAt(0).toUpperCase()+v.slice(1);if(v==='logs')loadLogs();if(v==='members'){window.loadMembers?.();window.loadRoles?.()}if(v==='overview')loadOverview();if(v==='announce')fillChannels();if(v==='routing')renderRouting();if(v==='control')window.loadServerControl?.();if(v==='chat')window.loadChat?.();if(v==='streams')window.loadStreams?.()}
window.navigate=showView;
window.addEventListener('popstate',()=>showView(viewFor(location.pathname),{noHistory:true}));
async function refreshGuilds(){const previous=String(state.guild||localStorage.getItem('rs_guild')||"");const g=await api("/api/guilds?_build="+encodeURIComponent(BUILD)+"&_t="+Date.now());state.guilds=Array.isArray(g)?g:[];const valid=state.guilds.some(x=>String(x.id)===previous);const next=valid?previous:(state.guilds[0]?String(state.guilds[0].id):null);rememberGuild(next);renderGuilds();if(!state.guilds.length)toast("No manageable servers found for this Discord account.");return state.guilds}
async function selectGuild(id){const wanted=String(id||"");if(!state.guilds.some(g=>String(g.id)===wanted)){await refreshGuilds()}if(!state.guilds.some(g=>String(g.id)===wanted)){toast("That server is no longer available to this Red Sentinel session.");return false}rememberGuild(wanted);const sel=$("#guildSelect");if(sel)sel.value=wanted;return true}
async function boot(){const au=$("#apiUrl"),at=$("#apiToken");if(au)au.value=state.api;if(at)at.value=state.token;if(location.hash.startsWith("#token=")){state.token=decodeURIComponent(location.hash.slice(7));localStorage.setItem("rs_token",state.token);history.replaceState({},document.title,location.pathname)}if(location.hash.startsWith("#session=")){state.token=decodeURIComponent(location.hash.slice(9));localStorage.setItem("rs_token",state.token);history.replaceState({},document.title,location.pathname)}try{await api("/api/health?_build="+encodeURIComponent(BUILD));const status=$("#apiStatus");if(status)status.textContent="API connected";await refreshGuilds();const initialView=viewFor(location.pathname);if(state.guild)showView(initialView,{noHistory:true});else if(status)status.textContent="API connected · no manageable servers";startPolling()}catch(e){const status=$("#apiStatus");if(status)status.textContent="API error";toast("API error: "+e.message)}}
function startPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(async()=>{if(document.hidden||!state.guild)return;try{const active=document.querySelector('.view.active')?.id||'';if(active==='view-logs')await loadLogs();else if(active==='view-control')await window.loadServerControl?.();else if(active==='view-streams')await window.loadStreams?.();else if(active==='view-chat'){return}else await loadOverview()}catch(e){console.debug("poll",e)}},7000)}
function renderGuilds(){const s=$("#guildSelect");if(!s)return;const current=String(state.guild||localStorage.getItem('rs_guild')||s.value||"");s.innerHTML=state.guilds.map(g=>`<option value="${String(g.id)}">◈ ${escapeHtml(g.name)}</option>`).join("");if(current&&state.guilds.some(g=>String(g.id)===current))s.value=current;else if(state.guilds[0]){s.value=String(state.guilds[0].id);rememberGuild(s.value)}}
async function loadOverview(){if(!state.guild)return;const known=state.guilds.some(g=>String(g.id)===String(state.guild));if(!known){await refreshGuilds();if(!state.guild)return}const gid=String(state.guild);const listed=state.guilds.find(x=>String(x.id)===gid);if(listed){const sm=$("#statMembers");if(sm)sm.textContent=listed.member_count??"—"}try{const g=await api(`/api/guilds/${gid}?_build=${BUILD}`);if(g){const sm=$("#statMembers");if(sm)sm.textContent=g.member_count??listed?.member_count??"—";fillChannels(g.channels)}}catch(e){if(String(e.message).includes("Guild not available")){await refreshGuilds();if(state.guild&&String(state.guild)!==gid)return loadOverview()}toast("Server unavailable: "+e.message);console.warn("Guild details failed",e);return}try{state.logs=await api(`/api/guilds/${gid}/events?limit=500&_build=${BUILD}`);renderLogs()}catch(e){state.logs=[];console.warn("Guild events failed",e)}try{state.config=await api(`/api/guilds/${gid}/config?_build=${BUILD}`);state.config=state.config||{providers:{},routes:{}}}catch(e){state.config={providers:{},routes:{}};console.warn("Guild config failed",e)}const se=$("#statEvents"),sr=$("#statRoutes"),act=$("#activity"),rc=$("#routeCards");if(se)se.textContent=state.logs.filter(x=>Number(x.created_at)>=Math.floor(new Date().setHours(0,0,0,0)/1000)).length;if(sr)sr.textContent=Object.keys(state.config.routes||{}).filter(k=>state.config.routes[k]).length;if(act)act.innerHTML=state.logs.slice(0,8).map(logRow).join("")||`<div class="hint">No events yet. Activity will appear as the bot observes your server.</div>`;if(rc)rc.innerHTML=["twitch","youtube","kick","x"].map(p=>`<div class="route"><b>${p.toUpperCase()}</b><i>${state.config.routes?.[p]?"● ROUTED":"○ NOT ROUTED"}</i></div>`).join("")}
async function loadLogs(){if(!state.guild)return;try{const type=$("#logType")?.value||"";state.logs=await api(`/api/guilds/${String(state.guild)}/events?limit=500${type?"&type="+encodeURIComponent(type):""}&_build=${encodeURIComponent(BUILD)}`);renderLogs()}catch(e){toast("Logs failed: "+e.message)}}
function renderLogs(){const table=$("#logTable");if(!table)return;const q=($("#logSearch")?.value||"").toLowerCase();table.innerHTML=state.logs.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).map(x=>`<tr><td>${time(x.created_at)}</td><td><span class="tag">${escapeHtml(x.type)}</span></td><td>${escapeHtml(x.actor_name||"System")}</td><td>${escapeHtml(x.channel_name||"—")}</td><td>${escapeHtml(detail(x))}</td></tr>`).join("")}
function logRow(x){return `<div class="activity-row"><div class="dot"></div><div><b>${escapeHtml(x.type)}</b><br><small>${escapeHtml(x.actor_name||"System")} ${x.channel_name?"in #"+escapeHtml(x.channel_name):""}</small></div><small>${time(x.created_at)}</small></div>`}
function detail(x){const p=x.payload||{};return String(p.content||p.reason||p.after||p.title||p.message_id||"Event received").slice(0,240)}
function time(s){return new Date(s*1000).toLocaleString([],{month:"short",day:"2-digit",hour:"2-digit",minute:"2-digit"})}
function fillChannels(channels){if(!channels)return;const texts=channels.filter(c=>c.type==="text");const ac=$("#announceChannel");if(ac)ac.innerHTML=texts.map(c=>`<option value="${c.id}"># ${escapeHtml(c.name)}</option>`).join("");renderRouting(channels)}
async function moderate(action){try{const body={user_id:$("#modUser")?.value||"",reason:$("#modReason")?.value||""};if(action==="timeout")body.minutes=60;await api(`/api/guilds/${String(state.guild)}/moderation/${action}`,{method:"POST",body:JSON.stringify(body)});toast(`${action} completed`);await loadLogs();await loadOverview()}catch(e){toast("Action failed: "+e.message)}}
async function deleteMessage(){try{await api(`/api/guilds/${String(state.guild)}/moderation/delete`,{method:"POST",body:JSON.stringify({channel_id:$("#deleteChannel")?.value||"",message_id:$("#deleteMessage")?.value||""})});toast("Message deleted");await loadLogs();await loadOverview()}catch(e){toast("Delete failed: "+e.message)}}
async function sendAnnouncement(){try{const content=$("#announceContent")?.value.trim()||"";const title=$("#embedTitle")?.value.trim()||"";const description=$("#embedDescription")?.value.trim()||"";const image=$("#embedImage")?.value.trim()||"";const colorRaw=$("#embedColor")?.value.trim()||"";const hasEmbed=!!(title||description||image);const body={channel_id:String($("#announceChannel")?.value||""),content};if(hasEmbed){const color=parseInt(colorRaw.replace("#",""),16);body.embed={};if(title)body.embed.title=title;if(description)body.embed.description=description;if(image)body.embed.image=image;if(Number.isFinite(color))body.embed.color=color}if(!content&&!hasEmbed)throw new Error("Write a message or add embed content first.");await api(`/api/guilds/${String(state.guild)}/announce`,{method:"POST",body:JSON.stringify(body)});toast("Announcement published");if($("#announceContent"))$("#announceContent").value="";await loadOverview()}catch(e){toast("Publish failed: "+e.message)}}
function previewAnnouncement(){const title=$("#embedTitle")?.value||"Announcement preview";const body=$("#embedDescription")?.value||$("#announceContent")?.value||"No content yet.";toast(`${title}: ${body.slice(0,90)}`)}
async function renderRouting(channels){if(!channels){try{channels=(await api(`/api/guilds/${String(state.guild)}?_build=${encodeURIComponent(BUILD)}`)).channels}catch(e){toast("Channels failed: "+e.message);return}}const texts=channels.filter(c=>c.type==="text"),form=$("#routingForm");if(!form)return;form.innerHTML=["twitch","youtube","kick","x","custom"].map(p=>`<label>${p.toUpperCase()} destination<select data-route="${p}"><option value="">Disabled</option>${texts.map(c=>`<option value="${c.id}" ${String(state.config.routes?.[p]||"")===String(c.id)?"selected":""}># ${escapeHtml(c.name)}</option>`).join("")}</select></label>`).join("")}
async function saveRouting(){const routes={};$$('[data-route]').forEach(s=>{if(s.value)routes[s.dataset.route]=s.value});try{await api(`/api/guilds/${String(state.guild)}/config`,{method:"PUT",body:JSON.stringify({routes})});toast("Routing saved");await loadOverview()}catch(e){toast("Save failed: "+e.message)}}
async function testSocial(){try{const provider=$("#testProvider")?.value||"custom",title=$("#testTitle")?.value||"Red Sentinel test signal",message=$("#testMessage")?.value||"Test";const r=await api("/api/webhooks/social",{method:"POST",body:JSON.stringify({guild_id:String(state.guild),provider,title,author:"Red Sentinel",description:message,url:`https://red-sentinel.netlify.app/?signal=${encodeURIComponent(provider)}`,external_id:`dashboard-test-${Date.now()}`})});toast(`Test signal delivered to ${r.delivered||0} channel(s)`);await loadOverview()}catch(e){toast("Test signal failed: "+e.message)}}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
Object.assign(window,{refreshGuilds,selectGuild,loadOverview,loadLogs,renderLogs,fillChannels,renderRouting,moderate,sendAnnouncement,saveRouting,deleteMessage,testSocial,previewAnnouncement,showView});
function bindUI(){const on=(id,event,fn)=>{const el=$(id);if(el)el.addEventListener(event,fn)};$$('.nav').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',e=>{e.preventDefault();showView(b.dataset.view)})});on('#viewAllLogs','click',()=>showView('logs'));on('#refreshBtn','click',async()=>{try{await refreshGuilds();await loadOverview()}catch(e){toast("Refresh failed: "+e.message)}});on('#logRefresh','click',loadLogs);on('#logType','change',loadLogs);on('#logSearch','input',renderLogs);on('#sendAnnounce','click',sendAnnouncement);on('#previewAnnounce','click',previewAnnouncement);on('#saveRouting','click',saveRouting);on('#deleteBtn','click',deleteMessage);on('#testSocial','click',testSocial);on('#banBtn','click',()=>moderate('ban'));on('#kickBtn','click',()=>moderate('kick'));on('#timeoutBtn','click',()=>moderate('timeout'));on('#guildSelect','change',async()=>{const ok=await selectGuild($("#guildSelect")?.value||"");if(ok){await loadOverview();window.loadChat?.();window.loadStreams?.()}});on('#saveConnection','click',()=>{state.api=$("#apiUrl")?.value.trim()||location.origin;state.token=$("#apiToken")?.value.trim()||"";localStorage.setItem("rs_api",state.api);localStorage.setItem("rs_token",state.token);boot()});on('#oauthLogin','click',()=>{state.api=$("#apiUrl")?.value.trim()||location.origin;localStorage.setItem("rs_api",state.api);location.href=state.api.replace(/\/$/,"")+"/oauth/discord/start"})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindUI,{once:true});else bindUI();
console.info("Red Sentinel dashboard",BUILD);boot();
