(()=>{
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const esc=s=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]));
const inject=()=>{if($('#chatView'))return;const nav=$$('.nav').find(x=>x.dataset.view==='streams');if(nav){const b=document.createElement('button');b.type='button';b.className='nav';b.dataset.view='chat';b.innerHTML='▣ <span>Server Chat</span>';nav.parentNode.insertBefore(b,nav)}const main=document.querySelector('main');if(!main)return;const s=document.createElement('section');s.id='view-chat';s.className='view';s.innerHTML=`<div class="chat-shell" id="chatView"><aside class="chat-channels"><div class="chat-side-head"><div><span class="eyebrow">SERVER MESSENGER</span><h3>Channels</h3></div><span class="chat-live">● LIVE</span></div><div id="chatChannelList" class="chat-channel-list"></div></aside><section class="chat-room"><header class="chat-room-head"><div><span class="eyebrow" id="chatCategory">CHANNEL</span><h2 id="chatRoomName">Select a channel</h2><p id="chatRoomMeta">Read the latest conversations from Discord.</p></div><div class="chat-room-actions"><input id="chatSearch" placeholder="Search loaded messages…"><button class="ghost" id="chatRefresh" type="button">↻ Refresh</button></div></header><div id="chatMessages" class="chat-messages"><div class="chat-empty">Select a text channel to open its conversation.</div></div><footer class="chat-compose"><textarea id="chatCompose" rows="2" maxlength="2000" placeholder="Message #channel…"></textarea><div class="chat-compose-foot"><span id="chatChars">0 / 2000</span><span>Enter to send · Shift+Enter for newline</span><button class="primary" id="chatSend" type="button">Send ↗</button></div></footer></section></div>`;main.appendChild(s);bind()};
let channel=null,messages=[],timer=null;
const api=(path,opts={})=>{const st=window.rsState;const h=Object.assign({'Content-Type':'application/json'},opts.headers||{});if(st?.token)h.Authorization=`Bearer ${st.token}`;return fetch((st?.api||location.origin).replace(/\/$/,'')+path,{...opts,headers:h,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error((await r.text())||`${r.status} ${r.statusText}`);return r.status===204?{}:r.json()})};
const channels=()=>window.rsState?.guilds?.length?api(`/api/guilds/${String(window.rsState.guild)}`).then(g=>g.channels||[]):Promise.resolve([]);
function renderChannels(list){const box=$('#chatChannelList');if(!box)return;const texts=list.filter(c=>c.type==='text');box.innerHTML=texts.map(c=>`<button type="button" class="chat-channel ${channel===String(c.id)?'active':''}" data-cid="${String(c.id)}"><span>#</span><b>${esc(c.name)}</b></button>`).join('')||'<div class="hint">No text channels available.</div>';$$('.chat-channel').forEach(b=>b.onclick=()=>openChannel(b.dataset.cid,list))}
async function openChannel(cid,list){channel=String(cid);renderChannels(list||await channels());const c=(list||[]).find(x=>String(x.id)===channel);$('#chatRoomName').textContent=c?`# ${c.name}`:'# channel';$('#chatRoomMeta').textContent='Latest 100 messages · live refresh';$('#chatCategory').textContent=c?.category?String(c.category).toUpperCase():'TEXT CHANNEL';await loadMessages();startLive()}
async function loadMessages(){if(!channel||!window.rsState.guild)return;try{messages=await api(`/api/guilds/${String(window.rsState.guild)}/channels/${channel}/messages?limit=100&_t=${Date.now()}`);renderMessages()}catch(e){$('#chatMessages').innerHTML=`<div class="chat-error">Unable to load conversation.<small>${esc(e.message)}</small></div>`}}
function renderMessages(){const box=$('#chatMessages');if(!box)return;const q=($('#chatSearch')?.value||'').toLowerCase();const arr=messages.filter(m=>!q||`${m.display_name} ${m.author} ${m.content}`.toLowerCase().includes(q));box.innerHTML=arr.length?arr.map((m,i)=>{const prev=arr[i-1],same=prev&&prev.author_id===m.author_id&&(m.created_at-prev.created_at)<300;const files=(m.attachments||[]).map(a=>`<a class="chat-attachment" href="${esc(a.url)}" target="_blank" rel="noopener">↗ ${esc(a.name)}</a>`).join('');const em=(m.embeds||[]).map(e=>`<div class="chat-embed">${e.title?`<b>${esc(e.title)}</b>`:''}${e.description?`<div>${esc(e.description)}</div>`:''}${e.url?`<a href="${esc(e.url)}" target="_blank" rel="noopener">Open link ↗</a>`:''}${e.image?`<img src="${esc(e.image)}" loading="lazy">`:''}</div>`).join('');return `<article class="chat-message ${same?'compact':''}" data-mid="${m.id}">${same?'<div class="chat-spacer"></div>':`<img class="chat-avatar" src="${esc(m.avatar||'')}" onerror="this.style.visibility='hidden'">`}<div class="chat-message-body">${same?'':`<div class="chat-author"><b>${esc(m.display_name)}</b><span>${esc(m.author)}</span><time>${new Date(m.created_at*1000).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time>${m.pinned?'<i>PINNED</i>':''}</div>`}<div class="chat-content">${esc(m.content).replace(/\n/g,'<br>')||''}</div>${files}${em}<div class="chat-msg-actions"><button type="button" data-delete="${m.id}">Delete</button></div></div></article>`}).join(''):`<div class="chat-empty"><strong>${q?'No matching messages':'No messages yet'}</strong><span>${q?'Try another search.':'This channel has no recent messages.'}</span></div>`;box.scrollTop=box.scrollHeight;$$('[data-delete]').forEach(b=>b.onclick=()=>deleteMessage(b.dataset.delete))}
async function deleteMessage(mid){if(!confirm('Delete this Discord message?'))return;try{await api(`/api/guilds/${String(window.rsState.guild)}/channels/${channel}/messages/${mid}`,{method:'DELETE'});window.toast?.('Message deleted');await loadMessages()}catch(e){window.toast?.('Delete failed: '+e.message)}}
async function send(){const el=$('#chatCompose'),content=el?.value.trim();if(!content||!channel)return;const btn=$('#chatSend');if(btn)btn.disabled=true;try{await api(`/api/guilds/${String(window.rsState.guild)}/channels/${channel}/messages`,{method:'POST',body:JSON.stringify({content})});el.value='';updateChars();await loadMessages()}catch(e){window.toast?.('Send failed: '+e.message)}finally{if(btn)btn.disabled=false;el?.focus()}}
function updateChars(){const el=$('#chatCompose'),c=$('#chatChars');if(c)c.textContent=`${el?.value.length||0} / 2000`}
async function boot(){try{const list=await channels();renderChannels(list);if(!channel&&list.find(c=>c.type==='text'))await openChannel(String(list.find(c=>c.type==='text').id),list)}catch(e){window.toast?.('Chat failed: '+e.message)}}
function startLive(){if(timer)clearInterval(timer);timer=setInterval(()=>{if(!document.hidden)loadMessages()},6000)}
function bind(){const sendBtn=$('#chatSend');sendBtn.onclick=send;$('#chatRefresh').onclick=loadMessages;$('#chatSearch').oninput=renderMessages;const compose=$('#chatCompose');compose.oninput=updateChars;compose.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};boot()}
inject();document.addEventListener('click',e=>{const n=e.target.closest?.('.nav[data-view="chat"]');if(n){e.preventDefault();const main=document.querySelector('#view-chat');$$('.view').forEach(x=>x.classList.toggle('active',x===main));$$('.nav').forEach(x=>x.classList.toggle('active',x===n));$('#pageTitle').textContent='Server Chat';boot()}});
})();
