(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; const S=window.rsState; if(!S)return;
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const api=(p,o={})=>{const h=Object.assign({"Content-Type":"application/json"},o.headers||{});if(S.token)h.Authorization=`Bearer ${S.token}`;return fetch(S.api.replace(/\/$/,"")+p,{...o,headers:h,cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error((await r.text())||`${r.status}`);return r.status===204?{}:r.json()})};
  const toast=t=>{const e=$("#toast");if(e){e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),3000)}};
  function install(){
    if(!$("#view-control")){const n=document.createElement("button");n.type="button";n.className="nav";n.dataset.view="control";n.innerHTML="▣ <span>Server Control</span>";$(".sidebar nav")?.insertBefore(n,$$(".nav").find(x=>x.dataset.view==="settings")||null);n.addEventListener("click",()=>show());
      const v=document.createElement("section");v.id="view-control";v.className="view";v.innerHTML=`<div class="grid-2"><div class="panel form-panel"><span class="eyebrow">SERVER</span><h3>Server settings</h3><label>Server name<input id="serverName" maxlength="100"></label><label>Description<input id="serverDescription" maxlength="1000"></label><button class="primary" id="serverSave">Save server</button></div><div class="panel form-panel"><span class="eyebrow">CHANNELS</span><h3>Channel control</h3><label>Name<input id="channelName" placeholder="general"></label><label>Type<select id="channelType"><option value="text">Text</option><option value="voice">Voice</option><option value="category">Category</option></select></label><label>Category ID (optional)<input id="channelCategory"></label><button class="primary" id="channelCreate">Create channel</button><div id="channelList" class="activity"></div></div></div><div class="grid-2"><div class="panel form-panel"><span class="eyebrow">ROLES</span><h3>Role control</h3><label>Role name<input id="roleName" placeholder="Moderator"></label><button class="primary" id="roleCreate">Create role</button><div id="roleList" class="activity"></div></div><div class="panel form-panel"><span class="eyebrow">AUDIT</span><h3>Discord audit log</h3><button class="ghost" id="auditRefresh">Refresh audit log</button><div id="auditList" class="activity"></div></div></div>`;$("main")?.appendChild(v);
      $("#serverSave")?.addEventListener("click",saveServer);$("#channelCreate")?.addEventListener("click",createChannel);$("#roleCreate")?.addEventListener("click",createRole);$("#auditRefresh")?.addEventListener("click",loadAudit);
    }
  }
  function show(){install(); if(window.showView)window.showView("control");loadControl()}
  async function loadControl(){if(!S.guild)return;try{const g=await api(`/api/guilds/${S.guild}`);$("#serverName").value=g.name||"";loadChannels();loadRoles()}catch(e){toast("Server control: "+e.message)}}
  async function loadChannels(){try{const d=await api(`/api/guilds/${S.guild}/channels`);$("#channelList").innerHTML=(d.channels||[]).map(c=>`<div class="activity-row"><div><b>${esc(c.name)}</b><small>${esc(c.type)} · ${c.id}</small></div><button class="ghost" data-crename="${c.id}" data-name="${esc(c.name)}">Rename</button><button class="danger" data-cdelete="${c.id}">Delete</button></div>`).join("")||`<div class="hint">No channels.</div>`;$$('[data-crename]').forEach(b=>b.onclick=async()=>{const name=prompt("New channel name",b.dataset.name);if(name)await channelAction("rename",{channel_id:b.dataset.crename,name})});$$('[data-cdelete]').forEach(b=>b.onclick=async()=>{if(confirm("Delete this channel?"))await channelAction("delete",{channel_id:b.dataset.cdelete})})}catch(e){$("#channelList").innerHTML=`<div class="hint">${esc(e.message)}</div>`}}
  async function channelAction(a,b){try{await api(`/api/guilds/${S.guild}/channels/${a}`,{method:"POST",body:JSON.stringify(b)});toast("Channel action completed");loadChannels();loadAudit()}catch(e){toast("Channel action failed: "+e.message)}}
  async function createChannel(){const name=$("#channelName").value.trim();if(!name)return toast("Channel name required");await channelAction("create",{name,type:$("#channelType").value,category_id:$("#channelCategory").value||null})}
  async function loadRoles(){try{const d=await api(`/api/guilds/${S.guild}/roles`);$("#roleList").innerHTML=(d.roles||[]).slice().reverse().map(r=>`<div class="activity-row"><div><b>${esc(r.name)}</b><small>${r.id} · position ${r.position}${r.managed?" · managed":""}</small></div>${!r.managed&&r.name!=="@everyone"?`<button class="ghost" data-rrename="${r.id}" data-name="${esc(r.name)}">Rename</button><button class="danger" data-rdelete="${r.id}">Delete</button>`:""}</div>`).join("");$$('[data-rrename]').forEach(b=>b.onclick=async()=>{const name=prompt("New role name",b.dataset.name);if(name)await roleAction("rename",{role_id:b.dataset.rrename,name})});$$('[data-rdelete]').forEach(b=>b.onclick=async()=>{if(confirm("Delete this role?"))await roleAction("delete",{role_id:b.dataset.rdelete})})}catch(e){$("#roleList").innerHTML=`<div class="hint">${esc(e.message)}</div>`}}
  async function roleAction(a,b){try{await api(`/api/guilds/${S.guild}/roles/${a}`,{method:"POST",body:JSON.stringify(b)});toast("Role action completed");loadRoles();loadAudit()}catch(e){toast("Role action failed: "+e.message)}}
  async function createRole(){const name=$("#roleName").value.trim();if(!name)return toast("Role name required");await roleAction("create",{name})}
  async function saveServer(){try{await api(`/api/guilds/${S.guild}/control/edit`,{method:"POST",body:JSON.stringify({name:$("#serverName").value,description:$("#serverDescription").value})});toast("Server saved");if(window.refreshGuilds)await window.refreshGuilds()}catch(e){toast("Server save failed: "+e.message)}}
  async function loadAudit(){try{const d=await api(`/api/guilds/${S.guild}/audit?limit=50`);$("#auditList").innerHTML=(d||[]).map(x=>`<div class="activity-row"><div><b>${esc(x.action)}</b><small>${esc(x.user?.name||"Unknown")} → ${esc(x.target||"—")}${x.reason?" · "+esc(x.reason):""}</small></div><small>${new Date(x.created_at*1000).toLocaleString()}</small></div>`).join("")||`<div class="hint">No audit entries.</div>`}catch(e){$("#auditList").innerHTML=`<div class="hint">${esc(e.message)}</div>`}}
  function bind(){install();$$('.nav').forEach(n=>{if(n.dataset.controlBound)return;n.dataset.controlBound='1';if(n.dataset.view==='control')n.addEventListener('click',show)});const old=window.showView;window.showView=v=>{old(v);if(v==='control')loadControl()};$("#guildSelect")?.addEventListener("change",()=>setTimeout(()=>{if($("#view-control")?.classList.contains("active"))loadControl()},100));}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
