(()=>{
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const st=window.rsState;let members=[],selected=null;
const api=(path,opts={})=>{const h=Object.assign({'Content-Type':'application/json'},opts.headers||{});if(st?.token)h.Authorization=`Bearer ${st.token}`;return fetch((st?.api||location.origin).replace(/\/$/,'')+path,{...opts,headers:h,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error((await r.text())||`${r.status} ${r.statusText}`);return r.status===204?{}:r.json()})};
function inject(){const view=$('#view-moderation');if(!view||view.dataset.polished)return;view.dataset.polished='1';const panel=view.querySelector('.form-panel');if(!panel)return;const h=panel.querySelector('h3');const picker=document.createElement('div');picker.className='mod-picker';picker.innerHTML=`<label>SELECT MEMBER <div class="mod-search-row"><input id="modMemberSearch" placeholder="Search username, display name or ID…"><button type="button" class="ghost" id="modRefreshMembers">↻</button></div></label><label>MEMBER<select id="modMemberSelect"><option value="">Select a member…</option></select></label><div id="modMemberCard" class="mod-member-card" hidden></div>`;h?.insertAdjacentElement('afterend',picker);const user=$('#modUser');if(user)user.closest('label')?.classList.add('mod-manual-id');}
function renderSelect(list){const s=$('#modMemberSelect');if(!s)return;s.innerHTML='<option value="">Select a member…</option>'+list.map(m=>`<option value="${esc(m.id)}">${esc(m.display_name||m.name)} · @${esc(m.name)}</option>`).join('');if(selected)s.value=String(selected.id)}
function renderCard(m){const card=$('#modMemberCard');if(!card)return;if(!m){card.hidden=true;card.innerHTML='';return}card.hidden=false;card.innerHTML=`<div class="mod-member-avatar-wrap"><img class="mod-member-avatar" src="${esc(m.avatar||'')}" alt="" onerror="this.style.visibility='hidden'"></div><div class="mod-member-main"><div class="mod-member-name"><strong>${esc(m.display_name||m.name)}</strong>${m.bot?'<span class="mod-bot">BOT</span>':''}</div><span class="mod-member-username">@${esc(m.name)} · ${esc(m.id)}</span><div class="mod-member-roles">${(m.roles||[]).map(r=>`<span style="--role-color:${esc(r.color||'#a78bfa')}">${esc(r.name)}</span>`).join('')||'<em>No roles</em>'}</div><div class="mod-member-meta"><span>${m.timeout_until?'⏳ Timed out':'● Active'}</span><span>${m.joined_at?'Joined '+new Date(m.joined_at).toLocaleDateString():'Join date unknown'}</span></div></div>`}
function selectMember(id){selected=members.find(m=>String(m.id)===String(id))||null;const input=$('#modUser');if(input)input.value=selected?String(selected.id):'';renderCard(selected)}
async function load(){if(!st?.guild)return;try{const data=await api(`/api/guilds/${String(st.guild)}/members?limit=500`);members=data.members||[];const q=($('#modMemberSearch')?.value||'').trim().toLowerCase();renderSelect(q?members.filter(m=>`${m.display_name} ${m.name} ${m.id}`.toLowerCase().includes(q)):members);if(selected)selectMember(selected.id)}catch(e){window.toast?.('Members failed: '+e.message)}}
async function doAction(name){const uid=String($('#modUser')?.value||'').trim();if(!uid)return window.toast?.('Select a member first.');const m=members.find(x=>String(x.id)===uid)||selected;const reason=String($('#modReason')?.value||'').trim();const info={ban:['Ban member?','This will permanently remove the member and block them from rejoining.'],kick:['Kick member?','The member will be removed from the server and may rejoin later.'],timeout:['Timeout member?','The member will be restricted from communicating for 1 hour.']}[name]||['Confirm action','Are you sure you want to continue?'];const r=await window.rsConfirm?.({action:name==='ban'?'Ban member':name==='kick'?'Kick member':'Timeout 1h',title:info[0],text:info[1],target:m?{name:m.display_name||m.name,username:m.name,avatar:m.avatar}:null,reason:true,danger:name!=='timeout'});if(!r?.confirmed)return;try{const body={user_id:uid,reason:reason||r.reason||`Red Sentinel ${name}`};if(name==='timeout')body.minutes=60;await api(`/api/guilds/${String(st.guild)}/moderation/${name}`,{method:'POST',body:JSON.stringify(body)});window.toast?.(`${name} completed`);await load();if(selected)selectMember(selected.id);await window.loadLogs?.();}catch(e){window.toast?.('Action failed: '+e.message)}}
function replaceButton(id,name){const old=$(id);if(!old||old.dataset.polished)return;const b=old.cloneNode(true);b.dataset.polished='1';old.replaceWith(b);b.addEventListener('click',()=>doAction(name))}
function bind(){inject();replaceButton('#banBtn','ban');replaceButton('#kickBtn','kick');replaceButton('#timeoutBtn','timeout');$('#modMemberSelect')?.addEventListener('change',e=>selectMember(e.target.value));let t;$('#modMemberSearch')?.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(load,180)});$('#modRefreshMembers')?.addEventListener('click',load);$('#modUser')?.addEventListener('input',e=>{const m=members.find(x=>String(x.id)===String(e.target.value).trim());if(m){selected=m;$('#modMemberSelect').value=String(m.id);renderCard(m)}});$('.nav[data-view="moderation"]')?.addEventListener('click',()=>setTimeout(load,80));$('#guildSelect')?.addEventListener('change',()=>setTimeout(load,140));load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else setTimeout(bind,20);window.loadModerationMembers=load;
})();
