(()=>{
  const $=s=>document.querySelector(s), state=window.rsState; if(!state)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api=(p,o={})=>{const h=Object.assign({'Content-Type':'application/json'},o.headers||{});if(state.token)h.Authorization=`Bearer ${state.token}`;return fetch(state.api.replace(/\/$/,'')+p,{...o,headers:h,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error((await r.text())||`${r.status}`);return r.status===204?{}:r.json()})};
  const toast=t=>{const e=$('#toast');if(e){e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)}};
  const icons={server:'✦',channel:'#',role:'◆',voice:'◖',settings:'⚙',search:'⌕',plus:'＋'};
  let channelCache=[],roleCache=[];
  function setup(){
    const nav=$('.sidebar nav');if(!nav)return;
    let b=nav.querySelector('[data-view="control"]');
    if(b){b.innerHTML=`<span class="nav-icon">${icons.server}</span><span>Server Control</span>`}
    else if(!nav.querySelector('[data-view="server"]')){b=document.createElement('button');b.type='button';b.className='nav';b.dataset.view='control';b.innerHTML=`<span class="nav-icon">${icons.server}</span><span>Server Control</span>`;nav.appendChild(b)}
    if($('#view-server'))return;
    const sec=document.createElement('section');sec.id='view-server';sec.className='view';sec.innerHTML=`
      <div class="sc-hero">
        <div><span class="sc-kicker">DISCORD OPERATIONS</span><h1>Server Control</h1><p>Manage channels, roles and server settings from one place.</p></div>
        <div class="sc-hero-status"><span class="sc-live-dot"></span><span>Sentinel online</span></div>
      </div>
      <div class="sc-stats" id="scStats"></div>
      <div class="server-control-grid">
        <section class="sc-panel sc-channels-panel">
          <div class="sc-panel-head"><div class="sc-heading"><span class="sc-icon">#</span><div><h2>Channel Control</h2><p>Create, edit or remove channels.</p></div></div><button class="primary sc-create-btn" id="scCreateToggle">${icons.plus} Create Channel</button></div>
          <div class="sc-create-form" id="scChannelForm">
            <div class="sc-form-grid"><label>Name<input id="scName" placeholder="new-channel"></label><label>Type<select id="scType"><option value="text">Text</option><option value="voice">Voice</option><option value="category">Category</option></select></label><label>Category ID <span class="hint">optional</span><input id="scCategory" placeholder="Category ID"></label></div>
            <div class="sc-form-actions"><button class="primary" id="scCreate">Create channel</button><button class="ghost" id="scCancelChannel">Cancel</button></div>
          </div>
          <div class="sc-toolbar"><label class="sc-search"><span>${icons.search}</span><input id="scChannelSearch" placeholder="Search channels..."></label><select id="scChannelType"><option value="all">All Types</option><option value="text">Text</option><option value="voice">Voice</option><option value="category">Category</option></select><select id="scChannelCategory"><option value="all">All Categories</option></select></div>
          <div id="scChannels" class="server-list sc-list"></div>
        </section>
        <section class="sc-panel sc-roles-panel">
          <div class="sc-panel-head"><div class="sc-heading"><span class="sc-icon role">◆</span><div><h2>Role Control</h2><p>Manage server roles and hierarchy.</p></div></div><button class="primary sc-create-btn" id="srCreateToggle">${icons.plus} Create Role</button></div>
          <div class="sc-create-form" id="scRoleForm">
            <div class="sc-form-grid role-form"><label>Name<input id="srName" placeholder="New Role"></label><label>Color<input id="srColor" placeholder="#7C5CFC"></label></div>
            <div class="sc-form-actions"><button class="primary" id="srCreate">Create role</button><button class="ghost" id="srCancel">Cancel</button></div>
          </div>
          <div class="sc-toolbar single"><label class="sc-search"><span>${icons.search}</span><input id="scRoleSearch" placeholder="Search roles..."></label></div>
          <div id="scRoles" class="server-list sc-list"></div>
        </section>
      </div>
      <section class="sc-panel sc-settings-panel">
        <div class="sc-panel-head"><div class="sc-heading"><span class="sc-icon">⚙</span><div><h2>Server Settings & Audit</h2><p>Basic server information and recent administrative activity.</p></div></div><div class="sc-audit-badge">AUDIT</div></div>
        <div class="sc-settings-grid"><div class="sc-settings-form"><label>Server name<input id="ssName"></label><label>Description<textarea id="ssDescription" rows="3" placeholder="Describe your community..."></textarea></label><div class="button-row"><button class="primary" id="ssSave">Save Changes</button><button class="ghost" id="saRefresh">Refresh audit</button></div></div><div class="sc-audit-wrap"><div class="sc-subhead"><span>Recent activity</span><small>Latest 50 entries</small></div><div id="scAudit" class="server-list server-audit"></div></div></div>
      </section>`;
    $('main').appendChild(sec);
    $('#scCreateToggle').onclick=()=>toggleForm('scChannelForm');$('#scCancelChannel').onclick=()=>toggleForm('scChannelForm',false);$('#srCreateToggle').onclick=()=>toggleForm('scRoleForm');$('#srCancel').onclick=()=>toggleForm('scRoleForm',false);
    $('#scCreate').onclick=createChannel;$('#srCreate').onclick=createRole;$('#ssSave').onclick=saveServer;$('#saRefresh').onclick=loadAudit;
    $('#scChannelSearch').oninput=renderChannelList;$('#scChannelType').onchange=renderChannelList;$('#scChannelCategory').onchange=renderChannelList;$('#scRoleSearch').oninput=renderRoleList;
  }
  function toggleForm(id,force){const e=$('#'+id);if(!e)return;e.classList.toggle('open',force===undefined?!e.classList.contains('open'):force)}
  function activate(){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-server'));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view==='control'||x.dataset.view==='server'));if($('#pageTitle'))$('#pageTitle').textContent='Server Control';loadServer()}
  function show(){activate()};window.showServerControl=show;window.loadServerControl=show;
  async function loadServer(){if(!state.guild)return;try{const g=await api(`/api/guilds/${state.guild}`);$('#ssName').value=g.name||'';$('#ssDescription').value=g.description||'';channelCache=g.channels||[];roleCache=(g.roles||[]).filter(r=>!r.managed);renderStats();renderCategoryFilter();renderChannelList();renderRoleList()}catch(e){toast('Server load failed: '+e.message)}loadAudit()}
  function renderStats(){const text=channelCache.filter(c=>c.type==='text').length,voice=channelCache.filter(c=>c.type==='voice').length,cats=channelCache.filter(c=>c.type==='category').length;$('#scStats').innerHTML=`<div class="sc-stat"><span class="sc-stat-icon">#</span><div><strong>${text}</strong><small>Text Channels</small></div></div><div class="sc-stat"><span class="sc-stat-icon voice">◖</span><div><strong>${voice}</strong><small>Voice Channels</small></div></div><div class="sc-stat"><span class="sc-stat-icon role">◆</span><div><strong>${roleCache.length}</strong><small>Roles</small></div></div><div class="sc-stat"><span class="sc-stat-icon member">♟</span><div><strong>${channelCache.length}</strong><small>Managed Objects</small></div></div>`}
  function renderCategoryFilter(){const s=$('#scChannelCategory');if(!s)return;const cats=channelCache.filter(c=>c.type==='category');s.innerHTML='<option value="all">All Categories</option>'+cats.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}
  function renderChannelList(){const q=($('#scChannelSearch')?.value||'').toLowerCase().trim(),type=$('#scChannelType')?.value||'all',cat=$('#scChannelCategory')?.value||'all';const cs=channelCache.filter(c=>(!q||String(c.name).toLowerCase().includes(q))&&(type==='all'||c.type===type)&&(cat==='all'||String(c.category_id||'')===cat));$('#scChannels').innerHTML=cs.map(c=>`<div class="server-item"><div class="server-item-main"><div class="server-item-title"><span class="sc-item-icon ${c.type==='voice'?'voice':''}">${c.type==='voice'?'◖':'#'}</span><strong>${esc(c.name)}</strong><span class="sc-chip">${esc(c.type)}</span>${c.category_name?`<span class="sc-chip muted">${esc(c.category_name)}</span>`:''}</div><small class="server-item-meta">ID ${esc(c.id)}</small></div><div class="server-item-actions"><button class="ghost" data-ch-rename="${c.id}">✎ Rename</button>${c.type!=='category'?`<button class="ghost" data-ch-slow="${c.id}">◷ Slowmode</button>`:''}<button class="danger" data-ch-del="${c.id}">▣ Delete</button></div></div>`).join('')||'<div class="sc-empty"><span>⌕</span><strong>No channels found</strong><small>Try a different search or filter.</small></div>';document.querySelectorAll('[data-ch-rename]').forEach(b=>b.onclick=()=>channelAction('rename',b.dataset.chRename));document.querySelectorAll('[data-ch-slow]').forEach(b=>b.onclick=()=>channelAction('slowmode',b.dataset.chSlow));document.querySelectorAll('[data-ch-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete this channel?'))channelAction('delete',b.dataset.chDel)})}
  function renderRoleList(){const q=($('#scRoleSearch')?.value||'').toLowerCase().trim(),rs=roleCache.filter(r=>!q||String(r.name).toLowerCase().includes(q));$('#scRoles').innerHTML=rs.map(r=>`<div class="server-item"><div class="server-item-main"><div class="server-item-title"><span class="role-color-dot" style="--role-color:${esc(r.color||'#7C5CFC')}"></span><strong>${esc(r.name)}</strong></div><small class="server-item-meta">Position ${esc(r.position)} · ID ${esc(r.id)}</small></div><div class="server-item-actions"><button class="ghost" data-rn="${r.id}">✎ Rename</button><button class="danger" data-rd="${r.id}">▣ Delete</button></div></div>`).join('')||'<div class="sc-empty"><span>◆</span><strong>No roles found</strong><small>Try another search.</small></div>';document.querySelectorAll('[data-rn]').forEach(b=>b.onclick=()=>roleAction('rename',b.dataset.rn));document.querySelectorAll('[data-rd]').forEach(b=>b.onclick=()=>{if(confirm('Delete this role?'))roleAction('delete',b.dataset.rd)})}
  async function createChannel(){try{await api(`/api/guilds/${state.guild}/channels/create`,{method:'POST',body:JSON.stringify({name:$('#scName').value,type:$('#scType').value,category_id:$('#scCategory').value})});toast('Channel created');toggleForm('scChannelForm',false);loadServer()}catch(e){toast('Channel failed: '+e.message)}}
  async function channelAction(action,id){let body={channel_id:id};if(action==='rename'){const n=prompt('New channel name');if(!n)return;body.name=n}if(action==='slowmode'){const n=prompt('Slowmode seconds (0-21600)','0');if(n===null)return;body.seconds=Number(n)}try{await api(`/api/guilds/${state.guild}/channels/${action}`,{method:'POST',body:JSON.stringify(body)});toast('Channel action completed');loadServer()}catch(e){toast('Channel action failed: '+e.message)}}
  async function createRole(){try{await api(`/api/guilds/${state.guild}/roles/create`,{method:'POST',body:JSON.stringify({name:$('#srName').value,color:$('#srColor').value})});toast('Role created');toggleForm('scRoleForm',false);loadServer()}catch(e){toast('Role failed: '+e.message)}}
  async function roleAction(action,id){let body={role_id:id};if(action==='rename'){const n=prompt('New role name');if(!n)return;body.name=n}try{await api(`/api/guilds/${state.guild}/roles/${action}`,{method:'POST',body:JSON.stringify(body)});toast('Role action completed');loadServer()}catch(e){toast('Role action failed: '+e.message)}}
  async function saveServer(){try{await api(`/api/guilds/${state.guild}/control/rename`,{method:'POST',body:JSON.stringify({name:$('#ssName').value})});await api(`/api/guilds/${state.guild}/control/description`,{method:'POST',body:JSON.stringify({description:$('#ssDescription').value})});toast('Server saved');loadServer()}catch(e){toast('Server save failed: '+e.message)}}
  async function loadAudit(){if(!state.guild)return;try{const d=await api(`/api/guilds/${state.guild}/audit?limit=50`);if(d.available===false){$('#scAudit').innerHTML=`<div class="audit-notice"><strong>Audit Log unavailable</strong><span>${esc(d.reason||'The Red Sentinel bot does not have permission to view the Discord audit log.')}</span><small>Give the bot <b>View Audit Log</b> permission in Discord if you want these entries here.</small></div>`;return}$('#scAudit').innerHTML=(d.entries||[]).slice(0,12).map(x=>`<div class="audit-row"><div><b>${esc(x.action)}</b><small>${esc(x.user||'Unknown')} → ${esc(x.target||'—')}</small></div><time>${new Date(x.created_at).toLocaleString()}</time></div>`).join('')||'<div class="sc-empty compact"><strong>No recent activity</strong><small>Administrative actions will appear here.</small></div>'}catch(e){$('#scAudit').innerHTML=`<div class="audit-notice"><strong>Audit Log unavailable</strong><span>${esc(e.message)}</span></div>`}}
  setup();
  document.addEventListener('click',e=>{const b=e.target.closest('.nav[data-view="control"],.nav[data-view="server"]');if(b){e.preventDefault();show()}});
  document.addEventListener('change',e=>{if(e.target.id==='guildSelect'&&document.querySelector('#view-server.active'))loadServer()});
})();
