(() => {
  const $=s=>document.querySelector(s), state=window.rsState; if(!state)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api=(p,o={})=>{const h=Object.assign({'Content-Type':'application/json'},o.headers||{});if(state.token)h.Authorization=`Bearer ${state.token}`;return fetch(state.api.replace(/\/$/,'')+p,{...o,headers:h,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error((await r.text())||`${r.status}`);return r.status===204?{}:r.json()})};
  const toast=t=>{const e=$('#toast');if(e){e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)}};
  const icons={server:'<svg viewBox="0 0 24 24"><rect x="4" y="4" width="16" height="6" rx="2"/><rect x="4" y="14" width="16" height="6" rx="2"/><path d="M7 7h.01M7 17h.01"/></svg>',channel:'<svg viewBox="0 0 24 24"><path d="M5 5h14a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2h-7l-4.5 4V16H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z"/><path d="M7 9h10M7 12h6"/></svg>',role:'<svg viewBox="0 0 24 24"><path d="m12 3 7 3.5V12c0 4.2-2.7 7.6-7 9-4.3-1.4-7-4.8-7-9V6.5z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></svg>'};
  function setup(){
    const nav=$('.sidebar nav'); if(!nav)return;
    let b=nav.querySelector('[data-view="control"]');
    if(b){b.innerHTML=`<span class="nav-icon">${icons.server}</span><span>Server Control</span>`;}
    else if(!nav.querySelector('[data-view="server"]')){b=document.createElement('button');b.type='button';b.className='nav';b.dataset.view='control';b.innerHTML=`<span class="nav-icon">${icons.server}</span><span>Server Control</span>`;nav.appendChild(b)}
    if($('#view-server'))return;
    const sec=document.createElement('section');sec.id='view-server';sec.className='view';sec.innerHTML=`<div class="server-control-grid"><div class="panel"><div class="server-panel-head"><div><span class="eyebrow">CHANNELS</span><h3>Channel control</h3></div><span class="server-panel-icon">${icons.channel}</span></div><div class="server-form-grid"><label>Name<input id="scName" placeholder="new-channel"></label><label>Type<select id="scType"><option value="text">Text</option><option value="voice">Voice</option><option value="category">Category</option></select></label></div><label>Category ID <span class="hint">optional</span><input id="scCategory" placeholder="Category ID"></label><button class="primary" id="scCreate">Create channel</button><div id="scChannels" class="server-list"></div></div><div class="panel"><div class="server-panel-head"><div><span class="eyebrow">ROLES</span><h3>Role control</h3></div><span class="server-panel-icon">${icons.role}</span></div><div class="server-form-grid"><label>Name<input id="srName" placeholder="New Role"></label><label>Color<input id="srColor" placeholder="#7C5CFC"></label></div><button class="primary" id="srCreate">Create role</button><div id="scRoles" class="server-list"></div></div></div><div class="panel server-settings"><div class="server-panel-head"><div><span class="eyebrow">SERVER</span><h3>Server settings & audit</h3></div><span class="server-panel-icon">${icons.server}</span></div><div class="grid-2 compact"><label>Server name<input id="ssName"></label><label>Description<input id="ssDescription"></label></div><div class="button-row"><button class="primary" id="ssSave">Save server</button><button class="ghost" id="saRefresh">Refresh audit log</button></div><div id="scAudit" class="server-list server-audit"></div></div>`;$('main').appendChild(sec);
    $('#scCreate').onclick=createChannel;$('#srCreate').onclick=createRole;$('#ssSave').onclick=saveServer;$('#saRefresh').onclick=loadAudit;
  }
  function activate(){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-server'));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view==='control'||x.dataset.view==='server'));$('#pageTitle').textContent='Server Control';loadServer()}
  function show(){activate()};window.showServerControl=show;window.loadServerControl=show;
  async function loadServer(){if(!state.guild)return;try{const g=await api(`/api/guilds/${state.guild}`);$('#ssName').value=g.name||'';$('#ssDescription').value=g.description||'';renderChannels(g.channels||[]);renderRoles(g.roles||[])}catch(e){toast('Server load failed: '+e.message)}loadAudit()}
  function renderChannels(cs){$('#scChannels').innerHTML=cs.map(c=>`<div class="server-item"><div class="server-item-main"><div class="server-item-title"><span class="server-type">${icons.channel} ${esc(c.type)}</span><strong>#${esc(c.name)}</strong></div><small class="server-item-meta">ID ${esc(c.id)}${c.category_id?` · Category ${esc(c.category_id)}`:''}</small></div><div class="server-item-actions"><button class="ghost" data-ch-rename="${c.id}">Rename</button><button class="ghost" data-ch-slow="${c.id}">Slowmode</button><button class="danger" data-ch-del="${c.id}">Delete</button></div></div>`).join('')||'<div class="hint">No channels.</div>';document.querySelectorAll('[data-ch-rename]').forEach(b=>b.onclick=()=>channelAction('rename',b.dataset.chRename));document.querySelectorAll('[data-ch-slow]').forEach(b=>b.onclick=()=>channelAction('slowmode',b.dataset.chSlow));document.querySelectorAll('[data-ch-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete this channel?'))channelAction('delete',b.dataset.chDel)})}
  function renderRoles(rs){$('#scRoles').innerHTML=rs.filter(r=>!r.managed).map(r=>`<div class="server-item"><div class="server-item-main"><div class="server-item-title"><span class="role-color-dot" style="--role-color:${esc(r.color||'#7C5CFC')}"></span><strong>${esc(r.name)}</strong></div><small class="server-item-meta">ID ${esc(r.id)} · position ${esc(r.position)}</small></div><div class="server-item-actions"><button class="ghost" data-rn="${r.id}">Rename</button><button class="danger" data-rd="${r.id}">Delete</button></div></div>`).join('')||'<div class="hint">No manageable roles.</div>';document.querySelectorAll('[data-rn]').forEach(b=>b.onclick=()=>roleAction('rename',b.dataset.rn));document.querySelectorAll('[data-rd]').forEach(b=>b.onclick=()=>{if(confirm('Delete this role?'))roleAction('delete',b.dataset.rd)})}
  async function createChannel(){try{await api(`/api/guilds/${state.guild}/channels/create`,{method:'POST',body:JSON.stringify({name:$('#scName').value,type:$('#scType').value,category_id:$('#scCategory').value})});toast('Channel created');loadServer()}catch(e){toast('Channel failed: '+e.message)}}
  async function channelAction(action,id){let body={channel_id:id};if(action==='rename'){const n=prompt('New channel name');if(!n)return;body.name=n}if(action==='slowmode'){const n=prompt('Slowmode seconds (0-21600)','0');if(n===null)return;body.seconds=Number(n)}try{await api(`/api/guilds/${state.guild}/channels/${action}`,{method:'POST',body:JSON.stringify(body)});toast('Channel action completed');loadServer()}catch(e){toast('Channel action failed: '+e.message)}}
  async function createRole(){try{await api(`/api/guilds/${state.guild}/roles/create`,{method:'POST',body:JSON.stringify({name:$('#srName').value,color:$('#srColor').value})});toast('Role created');loadServer()}catch(e){toast('Role failed: '+e.message)}}
  async function roleAction(action,id){let body={role_id:id};if(action==='rename'){const n=prompt('New role name');if(!n)return;body.name=n}try{await api(`/api/guilds/${state.guild}/roles/${action}`,{method:'POST',body:JSON.stringify(body)});toast('Role action completed');loadServer()}catch(e){toast('Role action failed: '+e.message)}}
  async function saveServer(){try{await api(`/api/guilds/${state.guild}/control/rename`,{method:'POST',body:JSON.stringify({name:$('#ssName').value})});await api(`/api/guilds/${state.guild}/control/description`,{method:'POST',body:JSON.stringify({description:$('#ssDescription').value})});toast('Server saved');loadServer()}catch(e){toast('Server save failed: '+e.message)}}
  async function loadAudit(){if(!state.guild)return;try{const d=await api(`/api/guilds/${state.guild}/audit?limit=50`);$('#scAudit').innerHTML=(d.entries||[]).map(x=>`<div class="audit-row"><div><b>${esc(x.action)}</b><br><small>${esc(x.user||'Unknown')} → ${esc(x.target||'—')}</small></div><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join('')||'<div class="hint">No audit entries.</div>'}catch(e){toast('Audit failed: '+e.message)}}
  setup();
  document.addEventListener('click',e=>{const b=e.target.closest('.nav[data-view="control"],.nav[data-view="server"]');if(b){e.preventDefault();show()}});
  document.addEventListener('change',e=>{if(e.target.id==='guildSelect'&&document.querySelector('#view-server.active'))loadServer()});
})();
